sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
script:
- export ENV_FILE=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  "stage"; fi`
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif [
  "$TRAVIS_BRANCH" == "develop" ]; then echo "stage"; else echo "dev-$(git rev-parse
  --short HEAD)"; fi`
- docker build --no-cache -t jincort/directcrypt-frontend-ico-dashboard-develop:${TAG} .
- docker run --rm -v $(pwd):/usr/src/app jincort/directcrypt-frontend-ico-dashboard-develop:${TAG}
  /bin/sh -c "yarn && cp -r .env.${ENV_FILE} .env && yarn build && yarn run lint:all"
after_success:
- export DOCKERFILE=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Dockerfile.stage";
  else echo "Dockerfile.prod" ; fi`
- docker build -f $DOCKERFILE --no-cache -t jincort/directcrypt-frontend-ico-dashboard:${TAG}
  .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push jincort/directcrypt-frontend-ico-dashboard-develop:${TAG}
- docker push jincort/directcrypt-frontend-ico-dashboard:${TAG}
notifications:
  slack:
    secure: ZRdhxdwpsHgXafGExFO51k2HhB9YAJLA2TG+/mcqJmqqRaizWJypPukBaqO+rp+G5rBbSg5wyABf2p6WlEzruBFghUwL6SVbb+ZAmvxOm1TDM6DdHcFLWSTREzvDaUYoADAwLO4vq/2I76B8dlhlbZN2ElJjGszRCUKSazjzmtToQxVZsy4iZVUfnb5x/6wE5T3vr5d950N4sSQrk/uqBG0v3QXJ9RJ0yLb+WJpJS1zjlSg4ojLV+qj7RQyLmoWotlF8L7B0PdxbSJfjuesyRlhB4nBgQFqKNTApjT7BcmaDVnU5JWsyJ41SovFO67hHMal2e7aK22Q8j9zjpC1w841tBG5kkRRS1mENUvpp1u65Ah18QMLcsb7M9H3IBH7AgvsvLFMn6zgptlDPezhRyJyMQy83GbfNl0PxSeIBEtO9hxyHCO3YzLPaDkwWljB6plUKSoN+6a3VR9k1sPQWdC69xus5skLQuK61hwS8yuTLobSBupL1Bw7j+0UqMbBGGvEalZ15QnfLFPlvbk7tG+1KexqIqDIivzX9XVpKxmOk68PfZ+mSDwQ0sivpZAUqjmRnk8f16W19eytGsm/fTEEN3x6KCdfEbKO+yGJXOxXAvi8xXmQ8HjQ4Q2Li5kdSIZn9G4dACMzdOqnZdvzH1lB7XNXOPFiXDoVm5zL09vU=
env:
  global:
  - secure: N88hGsEPHiivGuGKN6O4lSpdKbvvggNXzLWeUKyj4mzAlmH6hLZH+hDl1EEYTBnuxS6qUcIvxtdZazKMqH6QOLStc9q8V3k8FvurBIGrHkXUvug8A1Rciq70Pqi+lBAn0XRYl/SlLKEHGYZYUaUWNQcZbtQKz/fCejOAUQYhiaWolEC8KYdF2jgBkGlf3XZxcpHIaTIzIu78JJwCLoxPSQPZAXDGy7qZAVvkEpTm34n0vRtADa7lMlaCvxgn2gdT8M1qkjwxsCyatb9krdY++Ow4UREqVhmu5NChr+YzcD+fAB3iXpPwguKX8L48qMKL7ExVG9JutSUvd7ijGXHeE7I0gY9B7QPDO4F5JydUWHKYq3zvuSepndPlhShwevFETwZj6p8dxkW9pkIMsBrJkLKJ5dRtsVuz7j3ovslcwZckvA8/YeSURTEXpbB73sknr8yrjaTUSaiouOrg3ATPvQwt03vuLzRLW9WsdHbRpCOmk8xnjOBdFliEBbeEs06vo2vHnBN6QLcD2+7K/HYvgBsmYxxRZuj4B7gN173kmLMMYj0BgW5qhnd/y0FCQStrzYuCXC6p/Mhl4iysZktahu4ziNjPIc2AtLhA7qFIOrHASO2NWCn2rxU0pbPEaaPYCw/mN0NiLR1aIxQ4gDh7v2lYYlaKtkHmOHDgmvynBUk=
  - secure: Vj7ecuTa5/ZUjZH33AkjQR3D+6KaoVCdJMxhomvrQtcW8JXVTGnyqQGLh4RmZXEtkIX8KBPZ8zBr877zVNTVkNM9sURXigQVPMYn9uOKC1I7JmPP89jhfGDn3Q2oiYZN+f6xM2pP4pA8gTSmsov6WCUi1q5lRXFLjq4tDZgHxCJmpfiqImpB4E+wAzF+dNtYy3xhocWUIX+rh2XKSTF2WJr9NGZpleUzW5YKFvlGfdkvnXUlhATBjaHri8RSMXc4QgjIYiLCLjtS3Xa3bV3sL+dprs9W7JMVU9duUx4riievX+zzhIsOjPRwayDkP7fDFZBvD1bFjEGtbIoGGMpVdbZ/zls58I3t5j8y94VD8aU5nkURMcM6M0nwfIiIw2GRf4GYR8uiO5ggQlEYCZFR4TcVugyRykeMWNyUj4rpEX34dOQQeGBDint/7qliMN6ampQ/TGFh6j7BcwP88VXj2CJGXR8foIgpOzDzT3Bi1Joy6w5KI8Umz6rWc7MhW6V8yihtPAMYlxsnr0RLiqRG8Tz/r9gLVBwXNLulgtqLVW51TTtllIO3bx5voZ/tz4GeNEfRXqjiQpycNsFaDGRTS9rndZAi12bpVcrNP5yoRUAwom4lQaj36kO7ARP34n/+UizHKeSENHKGdSlBUbeFUWmLuJL/dYNmJatm9htfwRc=
